version: '3.4'
services:
  
  pdspi-mapper-parallex-example:
    build:
      context: .
    restart: always
    environment:
      INPUT_DIR: /shared
      OUTPUT_DIR: /shared
#      LOG_LEVEL: DEBUG
    ports:
      - $API_PORT:8080
    volumes:
      - ./config:/usr/src/app/config
      - $SHARED_DIR:/shared

networks:                      
  default:                     
    driver: bridge             
    ipam:                      
      driver: default          
      config:                  
        - subnet: ${SUBNET}
    
